// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

[Table("Guest")]
public partial class Guest
{
    [Key]
    [StringLength(25)]
    public string GuestId { get; set; }

    [StringLength(15)]
    public string PhoneNumber { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [InverseProperty("Guest")]
    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    [InverseProperty("Guest")]
    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}