// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagment.Models;

[PrimaryKey("BillNumber", "BookingId", "GuestId")]
[Table("Bill")]
public partial class Bill
{
    [Key]
    public int BillNumber { get; set; }

    [Key]
    public int BookingId { get; set; }

    [Key]
    public int GuestId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Total { get; set; }

    public bool IsPaid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("Bills")]
    public virtual Reservation Booking { get; set; }

    [ForeignKey("GuestId")]
    [InverseProperty("Bills")]
    public virtual Guest Guest { get; set; }
}