// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagment.Models;

[PrimaryKey("GuestId", "BookingId", "RoomId")]
[Table("GuestBookRoom")]
public partial class GuestBookRoom
{
    [Display(Name ="National Id")]
    [Key]
    public int GuestId { get; set; }

    [Key]
    public int BookingId { get; set; }

    [Key]
    public int RoomId { get; set; }

    public DateOnly CheckIn { get; set; }

    public DateOnly? CheckOut { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("GuestBookRooms")]
    public virtual Reservation Booking { get; set; }

    [ForeignKey("GuestId")]
    [InverseProperty("GuestBookRooms")]
    public virtual Guest Guest { get; set; }

    [ForeignKey("RoomId")]
    [InverseProperty("GuestBookRooms")]
    public virtual Room Room { get; set; }
}