// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagment.Models;

[Table("Reservation")]
public partial class Reservation
{
    [Key]
    public int BookingId { get; set; }

    public bool Valid { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    [InverseProperty("Booking")]
    public virtual ICollection<GuestBookRoom> GuestBookRooms { get; set; } = new List<GuestBookRoom>();

    [InverseProperty("Booking")]
    public virtual ICollection<ServiceOrder> ServiceOrders { get; set; } = new List<ServiceOrder>();
}