// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagment.Models;

[Table("Room")]
public partial class Room
{
    [Key]
    public int RoomId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }
    [Display(Name = "Room Number")]
    public int RoomNum { get; set; }
    public bool Availability { get; set; }

    [InverseProperty("Room")]
    public virtual ICollection<GuestBookRoom> GuestBookRooms { get; set; } = new List<GuestBookRoom>();
}