// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelManagment.Models;

[PrimaryKey("ServiceId", "BookingId", "GuestId", "OrderDate")]
[Table("ServiceOrder")]
public partial class ServiceOrder
{
    [Key]
    public int ServiceId { get; set; }

    [Key]
    public int BookingId { get; set; }

    [Key]
    public int GuestId { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Amount { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("ServiceOrders")]
    public virtual Reservation Booking { get; set; }

    [ForeignKey("GuestId")]
    [InverseProperty("ServiceOrders")]
    public virtual Guest Guest { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("ServiceOrders")]
    public virtual Service Service { get; set; }
}