// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

public partial class HotelElsayedContext : IdentityDbContext<ApplicationUser>
{
    public HotelElsayedContext(DbContextOptions<HotelElsayedContext> options):base(options)
    {
        
    }

    public virtual DbSet<Bill> Bills { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }
     
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bill>()
        .HasOne(b => b.ReservationNumberNavigation)
        .WithOne(b=>b.Bill)
        .OnDelete(DeleteBehavior.Restrict); // or .OnDelete(DeleteBehavior.NoAction);

        base.OnModelCreating(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}