// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

public partial class HotelElsayedContext : IdentityDbContext<ApplicationUser>
{
    public HotelElsayedContext(DbContextOptions<HotelElsayedContext> options):base(options)
    {
        
    }

    public virtual DbSet<Bill> Bills { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var x = ChangeTracker.Entries<IDeletable>().Where(state => state.State == EntityState.Deleted);
        foreach(var state in x)
        {
            state.Property(nameof(IDeletable.isDeleted)).CurrentValue = true;
            state.State = EntityState.Modified;
        }
        return base.SaveChangesAsync(cancellationToken);
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bill>()
        .HasOne(b => b.ReservationNumberNavigation)
        .WithOne(b=>b.Bill)
        .OnDelete(DeleteBehavior.Restrict); // or .OnDelete(DeleteBehavior.NoAction);
        modelBuilder.Entity<District>()
        .HasOne(d => d.DistrictGovernorate)
        .WithMany(g => g.Districts)
        .HasForeignKey(d => d.GovernorateId)
        .OnDelete(DeleteBehavior.NoAction); // No cascade delete

        modelBuilder.Entity<Room>().HasQueryFilter(r => !r.isDeleted); 

        // Configure District → Country
        modelBuilder.Entity<District>()
            .HasOne(d => d.DistrictCountry)
            .WithMany()
            .HasForeignKey(d => d.CountryId)
            .OnDelete(DeleteBehavior.NoAction); // No cascade delete

        // Configure Governorate → Country
        modelBuilder.Entity<Governorate>()
            .HasOne(g => g.GovernorateCountry)
            .WithMany()
            .HasForeignKey(g => g.CountryId)
            .OnDelete(DeleteBehavior.NoAction);
        base.OnModelCreating(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}