// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace ElSayedHotel.Models
{
    public interface IDeletable
    {
        public bool isDeleted { get; set; }
    }
}