// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

[Table("Reservation")]
public partial class Reservation
{
    [Key]
    public int ReservationNumber { get; set; }

    [Required]
    [StringLength(25)]
    public string GuestId { get; set; }

    public int RoomNumber { get; set; }

    public DateTime CheckIn { get; set; }

    public DateTime? CheckOut { get; set; }

    public bool? Active { get; set; }

    [InverseProperty("ReservationNumberNavigation")]
    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    [ForeignKey("GuestId")]
    [InverseProperty("Reservations")]
    public virtual Guest Guest { get; set; }

    [ForeignKey("RoomNumber")]
    [InverseProperty("Reservations")]
    public virtual Room RoomNumberNavigation { get; set; }

    [InverseProperty("ReservationNumberNavigation")]
    public virtual ICollection<ServiceOrder> ServiceOrders { get; set; } = new List<ServiceOrder>();
}