// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

[Table("Reservation")]
public partial class Reservation
{
    [Key]
    public int ReservationNumber { get; set; }

    [Required]
    [StringLength(450)]

    public string GuestId { get; set; }
    [Required]
    [StringLength(450)]

    public string OwnerId { get; set; }

    public Guid RoomId { get; set; }

    public DateTime CheckIn { get; set; }

    public DateTime? CheckOut { get; set; }

    public int? Status { get; set; } = 0; // 0 pending 1 confermed 2 canseled  
    public double? Total { get; set; }


    [InverseProperty("ReservationNumberNavigation")]
    public virtual Bill Bill { get; set; }

    [ForeignKey("GuestId")]
    [InverseProperty("Reservations")]
    public virtual ApplicationUser Guest { get; set; }

    [ForeignKey("RoomId")]
    [InverseProperty("Reservations")]
    public virtual Room RoomNavigation { get; set; }

}