// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

[Table("RoomType")]
public partial class RoomType
{
    [Key]
    [Column("RoomType")]
    public int RoomType1 { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    [InverseProperty("TypeNavigation")]
    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}