// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ElSayedHotel.Models;

[Table("Room")]
public partial class Room
{
    [Key]
    public int RoomNumber { get; set; }

    public double Price { get; set; }

    public bool Available { get; set; }

    public string Description { get; set; }

    public int roomType { get; set; }
    [StringLength(450)]
    public string ownerId { get; set; }


    [InverseProperty("RoomNumberNavigation")]
    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    [ForeignKey("roomType")]
    [InverseProperty("Rooms")]
    public virtual RoomType TypeNavigation { get; set; }
    [ForeignKey("ownerId")]
    public virtual ApplicationUser owner { get; set; }
    public string? ImageName { get; set; } // Store the image file name

    public string? ImagePath { get; set; } // Store the path to the image
}